name: Build package

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install build
      run: |
        python -m pip install build
    - name: Build sdist
      run: |
        python -m build --sdist --outdir sdist
    - uses: actions/upload-artifact@v4
      with:
        name: sdist-artifact
        path: ./sdist/*

