name: Build package

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install build
      run: |
        python -m pip install build
    - name: Build sdist
      run: |
        python -m build --sdist --outdir sdist
    - uses: actions/upload-artifact@v4
      with:
        name: sdist-artifact
        path: ./sdist/*


  build-wheels:
    name: Build wheels on ${{matrix.os.name}}
    runs-on: ${{matrix.os.name}}
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - name: ubuntu-20.04
          - name: windows-2019
          # - name: macOS-10.15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.16.2
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os.name}}-wheel-artifact
        path: ./wheelhouse/*.whl
