name: Integration test 

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    -cron: '0 0 13 * *'

jobs:
  integration-test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install tox
        run: |
          python -m pip install --upgrade pip && pip install tox 
      - name: Run tests
        run: |
          tox -e py38 -- -m "api"

